### ISSUE TITLE
How to use transactions if we inserting data in multiple tables using repostries

### ISSUE THREAD

**Issue by Anupam-** [Yoinbol/Dapper.DataRepositories#6]
Hi, I am using this in an ASP.NET MVC project , and looking for transaction based insertion and updation , can you please explain.

**Comment by Yoinbol** [comment]
Hi. I encourage you to use TransactionScope, is the best and easiest way I know to handle transactions. You can see an example here: 

https://github.com/Yoinbol/Dapper.DataRepositories.Demo/blob/master/Dapper.DataRepositories.Demo/Controllers/API/UsersController.cs

**Comment by Anupam-** [comment]
Thank you very much dear. Actually I was missing test cases here, 
 Thanks for sharing link for demo.
